[tcpout]
defaultGroup = splunk_cloud_proxy

[tcpout:splunk_cloud_proxy]
server = 10.250.5.12:8444
sslVerifyServerCert = true
sslRootCAPath = /etc/pki/tls/certs/icasa-ca.crt
useClientSSLCompression = true
compressed = true
